name: assignment-test

on:
    push:
        tags-ignore:
            - '*'
        branches:
            - 'assignment7-part1'

jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - name: Add Root CA Certificate to Container
            run: |
              /usr/bin/docker cp ~/ZscalerRootCA.crt $(/usr/bin/docker ps -q -f ancestor=cuaesd/aesd-autotest:24-unit-test):/usr/local/share/ca-certificates/
              /usr/bin/docker exec $(/usr/bin/docker ps -q -f ancestor=cuaesd/aesd-autotest:24-unit-test) update-ca-certificates
          - name: Verify Certificate Installation in Container
            run: |
              /usr/bin/docker exec $(/usr/bin/docker ps -q -f ancestor=cuaesd/aesd-autotest:24-unit-test) ls -l /etc/ssl/certs | grep "ZscalerRootCA"
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh

    full-test:
        container: cuaesd/aesd-autotest:24-assignment7
        runs-on: self-hosted
        steps:
          - name: Add Root CA Certificate to Container
            run: |
              /usr/bin/docker cp ~/ZscalerRootCA.crt $(/usr/bin/docker ps -q -f ancestor=cuaesd/aesd-autotest:24-assignment7):/usr/local/share/ca-certificates/
              /usr/bin/docker exec $(/usr/bin/docker ps -q -f ancestor=cuaesd/aesd-autotest:24-assignment7) update-ca-certificates
          - name: Verify Certificate Installation in Container
            run: |
              /usr/bin/docker exec $(/usr/bin/docker ps -q -f ancestor=cuaesd/aesd-autotest:24-assignment7) ls -l /etc/ssl/certs | grep "ZscalerRootCA"
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
