name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - 'assignment7-part1'
jobs:
    upload-cert:
        runs-on: self-hosted
        steps:
          - name: Upload Zscaler Root CA certificate
            uses: actions/upload-artifact@v2
            with:
              name: ZscalerRootCA
              path: ~/ZscalerRootCA.crt

    unit-test:
        needs: upload-cert
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - name: Download Zscaler Root CA certificate
            uses: actions/download-artifact@v2
            with:
              name: ZscalerRootCA
              path: ./ZscalerRootCA.crt
          - name: Copy Zscaler Root CA certificate
            run: |
              sudo cp ./ZscalerRootCA.crt /usr/local/share/ca-certificates/
              sudo update-ca-certificates
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh

    full-test:
        needs: upload-cert
        container: cuaesd/aesd-autotest:24-assignment7
        runs-on: self-hosted
        steps:
          - name: Download Zscaler Root CA certificate
            uses: actions/download-artifact@v2
            with:
              name: ZscalerRootCA
              path: ./ZscalerRootCA.crt
          - name: Copy Zscaler Root CA certificate
            run: |
              sudo cp ./ZscalerRootCA.crt /usr/local/share/ca-certificates/
              sudo update-ca-certificates
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
